language: c
compiler:
  - gcc
  - clang
sudo: false
script:
  - (mkdir build && cd build && cmake -DBUILD_TESTS=ON -DBUILD_GTEST=ON -DBUILD_GMOCK=OFF -G "Unix Makefiles" .. && make)
  - build/runTests
